romio/daos: conditionally compile on libdaos major version
daos-stack/mpich pull request #42
Opened 2020-12-01 02:59 UTC by mchaarawi

With this change the the DAOS ADIO driver conditionally compiles
to detect if it is being built against the original (before major
version 1) libdaos API, or the newer API. Major version 1 of
libdaos removes the need for daos clients to specify a pool service
replica rank list.

PR-repos: daos@PR-3935:3

Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

## Pull Request Description

## Expected Impact

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

2020-12-03 21:31 UTC, jolivier23 approved these changes

2020-12-03 23:15 UTC, mchaarawi commented
i created this PR from Ken's branch, so i can't add a +1, but +1

as discussed on Skype, if we also can make the group/sysname parameter go away, we should do that in the same set of changes we want to push upstream vs doing 2 API changes at different times.

2020-12-04 16:36 UTC, kccain commented
Thanks @mchaarawi . As discussed just now, a sequencing plan is to first get @brianjmurrell review of this and another ior-hpc repo change https://github.com/daos-stack/ior-hpc/pull/7/files , to land those two patches now, so that the back-compatible conditional compilation will, when testing with current daos master branch, refer to the existing libdaos major API version "v0".

In parallel to this I will take a look at hdf5 vol connector changes that can be done similarly, and Mohamad will help me land a diff upstream.

Then I can proceed asynchronously with the major API v1 update to daos in https://github.com/daos-stack/daos/pull/3935 

And then I can consider whether we can/should make any changes to the group/sysname parameters in libdaos API also as part of this major API v1 transition. If we determine yes then I could prepare similar PRs for ior-hpc, mpich and hdf5.. If we determine no, then no more changes to those use cases would be required.

2020-12-04 19:01 UTC, brianjmurrell requested changes
The `Release:` (and a corresponding `%changelog` entry) in the spec should be updated at minimum so that we don't overwrite the most recent version of this RPM that wants libdaos.so.0.

2020-12-04 19:40 UTC, brianjmurrell approved these changes

2020-12-04 19:50 UTC, kccain commented
> The `Release:` (and a corresponding `%changelog` entry) in the spec should be updated at minimum so that we don't overwrite the most recent version of this RPM that wants libdaos.so.0.

Trying to make sure how to address this in a reasonable way. What do you think of the following:

Immediate intent is to commit this as back-compatible and to have it test against current daos master branch with the existing libdaos.so.0 API. So, notionally, no spec updates in this PR (although if it is the right thing to do perhaps a Release, changelog, and more precise BuildRequires: daos-devel could be instituted now. e.g., daos-devel <= 1.1.2 ?

But assuming no spec change in this PR - the WIP DAOS PR would update major API version. And It would presumably (and I think I need to amend my daos PR 3995 as such) update the DAOS RPM package version numbers. So after the daos PR lands later, I could prepare mpich and ior-hpc pair of PRs to update their RPM spec files  to declare a requirement for daos-devel > 1.1.2. Does that make sense?

2020-12-04 19:58 UTC, brianjmurrell commented
> BuildRequires: daos-devel could be instituted now. e.g., daos-devel <= 1.1.2 ?

If the change is backwards compatible, this isn't necessary.
 
> I could prepare mpich and ior-hpc pair of PRs to update their RPM spec files to declare a requirement for daos-devel > 1.1.2.

Again, not necessary given the backwards compatibility.

2020-12-04 20:29 UTC, kccain commented
let me see if I can do a git commit amend to get rid of the commit pragma, to get a sanity check of this change built against daos master, rather than that WIP daos PR that provides v1 API.
PR-repos: daos@PR-3935:3

I've built and tested this change against daos master in my test environment, but probably makes sense to do here also.

2020-12-05 04:20 UTC, merged